// Copyright 2017 The ObjectHash-Proto Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is used for tests that involve floats.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: tests/api/v1/floats.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoubleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  float64   `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []float64 `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *DoubleMessage) Reset() {
	*x = DoubleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_floats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleMessage) ProtoMessage() {}

func (x *DoubleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_floats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleMessage.ProtoReflect.Descriptor instead.
func (*DoubleMessage) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_floats_proto_rawDescGZIP(), []int{0}
}

func (x *DoubleMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DoubleMessage) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type FloatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  float32   `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []float32 `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *FloatMessage) Reset() {
	*x = FloatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_floats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatMessage) ProtoMessage() {}

func (x *FloatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_floats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatMessage.ProtoReflect.Descriptor instead.
func (*FloatMessage) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_floats_proto_rawDescGZIP(), []int{1}
}

func (x *FloatMessage) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *FloatMessage) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_tests_api_v1_floats_proto protoreflect.FileDescriptor

var file_tests_api_v1_floats_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x0d, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x65, 0x72, 0x74, 0x6f, 0x2d, 0x64, 0x65, 0x76, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x68, 0x61, 0x73, 0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tests_api_v1_floats_proto_rawDescOnce sync.Once
	file_tests_api_v1_floats_proto_rawDescData = file_tests_api_v1_floats_proto_rawDesc
)

func file_tests_api_v1_floats_proto_rawDescGZIP() []byte {
	file_tests_api_v1_floats_proto_rawDescOnce.Do(func() {
		file_tests_api_v1_floats_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_api_v1_floats_proto_rawDescData)
	})
	return file_tests_api_v1_floats_proto_rawDescData
}

var file_tests_api_v1_floats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tests_api_v1_floats_proto_goTypes = []interface{}{
	(*DoubleMessage)(nil), // 0: tests.api.v1.DoubleMessage
	(*FloatMessage)(nil),  // 1: tests.api.v1.FloatMessage
}
var file_tests_api_v1_floats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_api_v1_floats_proto_init() }
func file_tests_api_v1_floats_proto_init() {
	if File_tests_api_v1_floats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_api_v1_floats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_floats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_api_v1_floats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_api_v1_floats_proto_goTypes,
		DependencyIndexes: file_tests_api_v1_floats_proto_depIdxs,
		MessageInfos:      file_tests_api_v1_floats_proto_msgTypes,
	}.Build()
	File_tests_api_v1_floats_proto = out.File
	file_tests_api_v1_floats_proto_rawDesc = nil
	file_tests_api_v1_floats_proto_goTypes = nil
	file_tests_api_v1_floats_proto_depIdxs = nil
}
