// Copyright 2017 The ObjectHash-Proto Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is used for tests that involve integers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: tests/api/v1/integers.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fixed32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  uint32   `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []uint32 `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Fixed32Message) Reset() {
	*x = Fixed32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fixed32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixed32Message) ProtoMessage() {}

func (x *Fixed32Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixed32Message.ProtoReflect.Descriptor instead.
func (*Fixed32Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{0}
}

func (x *Fixed32Message) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Fixed32Message) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Fixed64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  uint64   `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []uint64 `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Fixed64Message) Reset() {
	*x = Fixed64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fixed64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixed64Message) ProtoMessage() {}

func (x *Fixed64Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixed64Message.ProtoReflect.Descriptor instead.
func (*Fixed64Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{1}
}

func (x *Fixed64Message) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Fixed64Message) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  int32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []int32 `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Int32Message) Reset() {
	*x = Int32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Message) ProtoMessage() {}

func (x *Int32Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Message.ProtoReflect.Descriptor instead.
func (*Int32Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{2}
}

func (x *Int32Message) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Int32Message) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  int64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []int64 `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Int64Message) Reset() {
	*x = Int64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Message) ProtoMessage() {}

func (x *Int64Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Message.ProtoReflect.Descriptor instead.
func (*Int64Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{3}
}

func (x *Int64Message) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Int64Message) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Sfixed32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  int32   `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []int32 `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Sfixed32Message) Reset() {
	*x = Sfixed32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sfixed32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sfixed32Message) ProtoMessage() {}

func (x *Sfixed32Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sfixed32Message.ProtoReflect.Descriptor instead.
func (*Sfixed32Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{4}
}

func (x *Sfixed32Message) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sfixed32Message) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Sfixed64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  int64   `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []int64 `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Sfixed64Message) Reset() {
	*x = Sfixed64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sfixed64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sfixed64Message) ProtoMessage() {}

func (x *Sfixed64Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sfixed64Message.ProtoReflect.Descriptor instead.
func (*Sfixed64Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{5}
}

func (x *Sfixed64Message) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sfixed64Message) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Sint32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  int32   `protobuf:"zigzag32,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []int32 `protobuf:"zigzag32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Sint32Message) Reset() {
	*x = Sint32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sint32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sint32Message) ProtoMessage() {}

func (x *Sint32Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sint32Message.ProtoReflect.Descriptor instead.
func (*Sint32Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{6}
}

func (x *Sint32Message) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sint32Message) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Sint64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  int64   `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []int64 `protobuf:"zigzag64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Sint64Message) Reset() {
	*x = Sint64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sint64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sint64Message) ProtoMessage() {}

func (x *Sint64Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sint64Message.ProtoReflect.Descriptor instead.
func (*Sint64Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{7}
}

func (x *Sint64Message) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Sint64Message) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Uint32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []uint32 `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Uint32Message) Reset() {
	*x = Uint32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32Message) ProtoMessage() {}

func (x *Uint32Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32Message.ProtoReflect.Descriptor instead.
func (*Uint32Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{8}
}

func (x *Uint32Message) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Uint32Message) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Uint64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Values []uint64 `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Uint64Message) Reset() {
	*x = Uint64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_integers_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64Message) ProtoMessage() {}

func (x *Uint64Message) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_integers_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64Message.ProtoReflect.Descriptor instead.
func (*Uint64Message) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_integers_proto_rawDescGZIP(), []int{9}
}

func (x *Uint64Message) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Uint64Message) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_tests_api_v1_integers_proto protoreflect.FileDescriptor

var file_tests_api_v1_integers_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74,
	0x65, 0x73, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x3e, 0x0a, 0x0e, 0x46,
	0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x07, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x0e, 0x46,
	0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x06, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x49,
	0x6e, 0x74, 0x33, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x49, 0x6e, 0x74,
	0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x53, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x33, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0f,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x53, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x10, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x10, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x11,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x12, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x55, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x65, 0x72, 0x74, 0x6f, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x68, 0x61, 0x73, 0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tests_api_v1_integers_proto_rawDescOnce sync.Once
	file_tests_api_v1_integers_proto_rawDescData = file_tests_api_v1_integers_proto_rawDesc
)

func file_tests_api_v1_integers_proto_rawDescGZIP() []byte {
	file_tests_api_v1_integers_proto_rawDescOnce.Do(func() {
		file_tests_api_v1_integers_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_api_v1_integers_proto_rawDescData)
	})
	return file_tests_api_v1_integers_proto_rawDescData
}

var file_tests_api_v1_integers_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tests_api_v1_integers_proto_goTypes = []interface{}{
	(*Fixed32Message)(nil),  // 0: tests.api.v1.Fixed32Message
	(*Fixed64Message)(nil),  // 1: tests.api.v1.Fixed64Message
	(*Int32Message)(nil),    // 2: tests.api.v1.Int32Message
	(*Int64Message)(nil),    // 3: tests.api.v1.Int64Message
	(*Sfixed32Message)(nil), // 4: tests.api.v1.Sfixed32Message
	(*Sfixed64Message)(nil), // 5: tests.api.v1.Sfixed64Message
	(*Sint32Message)(nil),   // 6: tests.api.v1.Sint32Message
	(*Sint64Message)(nil),   // 7: tests.api.v1.Sint64Message
	(*Uint32Message)(nil),   // 8: tests.api.v1.Uint32Message
	(*Uint64Message)(nil),   // 9: tests.api.v1.Uint64Message
}
var file_tests_api_v1_integers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_api_v1_integers_proto_init() }
func file_tests_api_v1_integers_proto_init() {
	if File_tests_api_v1_integers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_api_v1_integers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fixed32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fixed64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sfixed32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sfixed64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sint32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sint64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_api_v1_integers_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_api_v1_integers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_api_v1_integers_proto_goTypes,
		DependencyIndexes: file_tests_api_v1_integers_proto_depIdxs,
		MessageInfos:      file_tests_api_v1_integers_proto_msgTypes,
	}.Build()
	File_tests_api_v1_integers_proto = out.File
	file_tests_api_v1_integers_proto_rawDesc = nil
	file_tests_api_v1_integers_proto_goTypes = nil
	file_tests_api_v1_integers_proto_depIdxs = nil
}
