// Copyright 2017 The ObjectHash-Proto Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: tests/api/v1/planets.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Planet int32

const (
	Planet_PLANET_UNKNOWN Planet = 0
	Planet_PLANET_EARTH   Planet = 3
	Planet_PLANET_MERCURY Planet = 1
	Planet_PLANET_VENUS   Planet = 2
	Planet_PLANET_MARS    Planet = 4
	Planet_PLANET_JUPITER Planet = 5
	Planet_PLANET_SATURN  Planet = 6
)

// Enum value maps for Planet.
var (
	Planet_name = map[int32]string{
		0: "PLANET_UNKNOWN",
		3: "PLANET_EARTH",
		1: "PLANET_MERCURY",
		2: "PLANET_VENUS",
		4: "PLANET_MARS",
		5: "PLANET_JUPITER",
		6: "PLANET_SATURN",
	}
	Planet_value = map[string]int32{
		"PLANET_UNKNOWN": 0,
		"PLANET_EARTH":   3,
		"PLANET_MERCURY": 1,
		"PLANET_VENUS":   2,
		"PLANET_MARS":    4,
		"PLANET_JUPITER": 5,
		"PLANET_SATURN":  6,
	}
)

func (x Planet) Enum() *Planet {
	p := new(Planet)
	*p = x
	return p
}

func (x Planet) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Planet) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_api_v1_planets_proto_enumTypes[0].Descriptor()
}

func (Planet) Type() protoreflect.EnumType {
	return &file_tests_api_v1_planets_proto_enumTypes[0]
}

func (x Planet) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Planet.Descriptor instead.
func (Planet) EnumDescriptor() ([]byte, []int) {
	return file_tests_api_v1_planets_proto_rawDescGZIP(), []int{0}
}

type MyFavoritePlanets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planets []Planet `protobuf:"varint,1,rep,packed,name=planets,proto3,enum=tests.api.v1.Planet" json:"planets,omitempty"`
}

func (x *MyFavoritePlanets) Reset() {
	*x = MyFavoritePlanets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_api_v1_planets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyFavoritePlanets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyFavoritePlanets) ProtoMessage() {}

func (x *MyFavoritePlanets) ProtoReflect() protoreflect.Message {
	mi := &file_tests_api_v1_planets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyFavoritePlanets.ProtoReflect.Descriptor instead.
func (*MyFavoritePlanets) Descriptor() ([]byte, []int) {
	return file_tests_api_v1_planets_proto_rawDescGZIP(), []int{0}
}

func (x *MyFavoritePlanets) GetPlanets() []Planet {
	if x != nil {
		return x.Planets
	}
	return nil
}

var File_tests_api_v1_planets_proto protoreflect.FileDescriptor

var file_tests_api_v1_planets_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x43, 0x0a, 0x11, 0x4d, 0x79,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x12,
	0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x2a,
	0x8c, 0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4c,
	0x41, 0x4e, 0x45, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x50, 0x4c, 0x41, 0x4e, 0x45, 0x54, 0x5f, 0x45, 0x41, 0x52, 0x54, 0x48, 0x10, 0x03,
	0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4c, 0x41, 0x4e, 0x45, 0x54, 0x5f, 0x4d, 0x45, 0x52, 0x43, 0x55,
	0x52, 0x59, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x4c, 0x41, 0x4e, 0x45, 0x54, 0x5f, 0x56,
	0x45, 0x4e, 0x55, 0x53, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x4e, 0x45, 0x54,
	0x5f, 0x4d, 0x41, 0x52, 0x53, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4c, 0x41, 0x4e, 0x45,
	0x54, 0x5f, 0x4a, 0x55, 0x50, 0x49, 0x54, 0x45, 0x52, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x50,
	0x4c, 0x41, 0x4e, 0x45, 0x54, 0x5f, 0x53, 0x41, 0x54, 0x55, 0x52, 0x4e, 0x10, 0x06, 0x42, 0x32,
	0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x65,
	0x72, 0x74, 0x6f, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x68, 0x61, 0x73,
	0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_api_v1_planets_proto_rawDescOnce sync.Once
	file_tests_api_v1_planets_proto_rawDescData = file_tests_api_v1_planets_proto_rawDesc
)

func file_tests_api_v1_planets_proto_rawDescGZIP() []byte {
	file_tests_api_v1_planets_proto_rawDescOnce.Do(func() {
		file_tests_api_v1_planets_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_api_v1_planets_proto_rawDescData)
	})
	return file_tests_api_v1_planets_proto_rawDescData
}

var file_tests_api_v1_planets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tests_api_v1_planets_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_api_v1_planets_proto_goTypes = []interface{}{
	(Planet)(0),               // 0: tests.api.v1.Planet
	(*MyFavoritePlanets)(nil), // 1: tests.api.v1.MyFavoritePlanets
}
var file_tests_api_v1_planets_proto_depIdxs = []int32{
	0, // 0: tests.api.v1.MyFavoritePlanets.planets:type_name -> tests.api.v1.Planet
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tests_api_v1_planets_proto_init() }
func file_tests_api_v1_planets_proto_init() {
	if File_tests_api_v1_planets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_api_v1_planets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyFavoritePlanets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_api_v1_planets_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_api_v1_planets_proto_goTypes,
		DependencyIndexes: file_tests_api_v1_planets_proto_depIdxs,
		EnumInfos:         file_tests_api_v1_planets_proto_enumTypes,
		MessageInfos:      file_tests_api_v1_planets_proto_msgTypes,
	}.Build()
	File_tests_api_v1_planets_proto = out.File
	file_tests_api_v1_planets_proto_rawDesc = nil
	file_tests_api_v1_planets_proto_goTypes = nil
	file_tests_api_v1_planets_proto_depIdxs = nil
}
